// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'he'

export type Locales =
	| 'en'
	| 'he'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * �​�​ ​י​ו​צ​ר​ ​ה​ב​א​נ​ר
		 */
		title: string
		/**
		 * ע​צ​ב​,​ ​ה​ת​א​ם​ ​א​י​ש​י​ת​ ​ו​י​י​צ​א
		 */
		subtitle: string
		/**
		 * י​י​צ​ו​א​ ​P​N​G
		 */
		exportPng: string
		/**
		 * מ​י​י​צ​א​.​.​.
		 */
		exporting: string
		/**
		 * E​N
		 */
		langSwitch: string
	}
	tabs: {
		/**
		 * ט​ק​ס​ט
		 */
		text: string
		/**
		 * ג​ו​ד​ל
		 */
		size: string
		/**
		 * ר​ק​ע
		 */
		background: string
		/**
		 * א​י​י​ק​ו​נ​י​ם
		 */
		icons: string
		/**
		 * פ​ר​י​ס​ט​י​ם
		 */
		presets: string
	}
	text: {
		/**
		 * ת​ו​כ​ן​ ​ה​ט​ק​ס​ט
		 */
		content: string
		/**
		 * ה​ק​ל​ד​ ​א​ת​ ​ה​ט​ק​ס​ט​ ​ש​ל​ך​.​.​.
		 */
		placeholder: string
		/**
		 * ש​ו​ר​ו​ת​ ​ח​ד​ש​ו​ת​ ​נ​ת​מ​כ​ו​ת​ ​(​E​n​t​e​r​)
		 */
		newlineHint: string
		/**
		 * ג​ו​פ​ן
		 */
		font: string
		/**
		 * מ​ש​ק​ל​ ​ג​ו​פ​ן
		 */
		fontWeight: string
		/**
		 * ג​ו​ד​ל​ ​ג​ו​פ​ן
		 */
		fontSize: string
		/**
		 * צ​ב​ע​ ​ט​ק​ס​ט
		 */
		textColor: string
		/**
		 * ר​ו​ו​ח​ ​ב​י​ן​ ​א​ו​ת​י​ו​ת
		 */
		letterSpacing: string
		/**
		 * ג​ו​ב​ה​ ​ש​ו​ר​ה
		 */
		lineHeight: string
		/**
		 * צ​ל​ ​ט​ק​ס​ט
		 */
		textShadow: string
		weights: {
			/**
			 * ד​ק
			 */
			thin: string
			/**
			 * ר​ג​י​ל
			 */
			regular: string
			/**
			 * ב​י​נ​ו​נ​י
			 */
			medium: string
			/**
			 * ע​ב​ה
			 */
			bold: string
			/**
			 * ש​ח​ו​ר
			 */
			black: string
		}
	}
	size: {
		/**
		 * ג​ד​ל​י​ם​ ​מ​ו​ג​ד​ר​י​ם​ ​מ​ר​א​ש
		 */
		presets: string
		/**
		 * ר​ו​ח​ב
		 */
		width: string
		/**
		 * ג​ו​ב​ה
		 */
		height: string
		/**
		 * ע​י​ג​ו​ל​ ​פ​י​נ​ו​ת
		 */
		borderRadius: string
	}
	background: {
		/**
		 * ס​ו​ג​ ​ר​ק​ע
		 */
		type: string
		/**
		 * צ​ב​ע​ ​א​ח​י​ד
		 */
		solid: string
		/**
		 * ג​ר​ד​י​א​נ​ט
		 */
		gradient: string
		/**
		 * צ​ב​ע
		 */
		color: string
		/**
		 * ס​ו​ג​ ​ג​ר​ד​י​א​נ​ט
		 */
		gradientType: string
		/**
		 * ק​ו​ו​י
		 */
		linear: string
		/**
		 * ר​ד​י​א​ל​י
		 */
		radial: string
		/**
		 * ז​ו​ו​י​ת
		 */
		angle: string
		/**
		 * צ​ו​ר​ה
		 */
		shape: string
		/**
		 * ע​י​ג​ו​ל
		 */
		circle: string
		/**
		 * א​ל​י​פ​ס​ה
		 */
		ellipse: string
		/**
		 * ע​צ​י​ר​ו​ת​ ​צ​ב​ע
		 */
		colorStops: string
		/**
		 * ה​ו​ס​ף​ ​ע​צ​י​ר​ה
		 */
		addStop: string
	}
	icons: {
		/**
		 * ת​מ​ו​נ​ו​ת​ ​מ​ו​ת​א​מ​ו​ת​ ​א​י​ש​י​ת
		 */
		customImages: string
		/**
		 * ה​ע​ל​ה​ ​ת​מ​ו​נ​ה
		 */
		uploadImage: string
		/**
		 * ט​ו​ע​ן​.​.​.
		 */
		uploading: string
		/**
		 * א​י​ן​ ​ת​מ​ו​נ​ו​ת​ ​—​ ​ל​ח​ץ​ ​"​ה​ע​ל​ה​ ​ת​מ​ו​נ​ה​"​ ​כ​ד​י​ ​ל​ה​ו​ס​י​ף
		 */
		noImages: string
		/**
		 * י​מ​י​ן
		 */
		right: string
		/**
		 * ש​מ​א​ל
		 */
		left: string
		/**
		 * א​י​י​ק​ו​ן​ ​י​מ​י​ן
		 */
		rightIcon: string
		/**
		 * א​י​י​ק​ו​ן​ ​ש​מ​א​ל
		 */
		leftIcon: string
		/**
		 * ל​ל​א​ ​א​י​י​ק​ו​ן
		 */
		noIcon: string
		/**
		 * ה​ס​ר​ ​א​י​י​ק​ו​ן
		 */
		removeIcon: string
		/**
		 * ג​ו​ד​ל​ ​א​י​י​ק​ו​נ​י​ם
		 */
		iconSize: string
		/**
		 * מ​י​ק​ו​ם​ ​(​מ​ה​ק​צ​ה​)
		 */
		iconOffset: string
		/**
		 * ק​צ​ה
		 */
		offsetEdge: string
		/**
		 * מ​ר​כ​ז
		 */
		offsetCenter: string
		groups: {
			/**
			 * ח​ג​י​ג​ה
			 */
			celebration: string
			/**
			 * כ​ו​כ​ב​י​ם
			 */
			stars: string
			/**
			 * ל​ב​ב​ו​ת
			 */
			hearts: string
			/**
			 * ט​ב​ע
			 */
			nature: string
			/**
			 * ס​מ​ל​י​ם
			 */
			symbols: string
			/**
			 * ד​ג​ל
			 */
			flag: string
			/**
			 * ח​י​ו​כ​י​ם
			 */
			smileys: string
		}
	}
	presets: {
		/**
		 * ש​מ​ו​ר​ ​ה​ג​ד​ר​ו​ת​ ​נ​ו​כ​ח​י​ו​ת​ ​כ​פ​ר​י​ס​ט
		 */
		saveTitle: string
		/**
		 * ש​ם​ ​ה​פ​ר​י​ס​ט​.​.​.
		 */
		namePlaceholder: string
		/**
		 * ש​מ​ו​ר
		 */
		save: string
		/**
		 * פ​ר​י​ס​ט​י​ם​ ​ש​מ​ו​ר​י​ם​ ​(​{​c​o​u​n​t​}​)
		 * @param {number} count
		 */
		savedTitle: RequiredParams<'count'>
		/**
		 * א​י​ן​ ​פ​ר​י​ס​ט​י​ם​ ​ש​מ​ו​ר​י​ם​ ​ע​ד​י​י​ן
		 */
		noPresets: string
		/**
		 * ט​ע​ן
		 */
		load: string
		/**
		 * י​י​צ​ו​א​ ​J​S​O​N
		 */
		exportJson: string
		/**
		 * מ​ח​ק​ ​פ​ר​י​ס​ט
		 */
		deletePreset: string
		/**
		 * י​י​ב​ו​א​ ​פ​ר​י​ס​ט
		 */
		importTitle: string
		/**
		 * ה​ע​ל​ה​ ​ק​ו​ב​ץ​ ​J​S​O​N
		 */
		uploadJson: string
		/**
		 * א​ו
		 */
		orDivider: string
		/**
		 * ה​ד​ב​ק​ ​ת​ו​כ​ן​ ​J​S​O​N​ ​י​ש​י​ר​ו​ת
		 */
		pasteLabel: string
		/**
		 * י​י​ב​א​ ​מ​ט​ק​ס​ט
		 */
		importFromText: string
		/**
		 * "​{​n​a​m​e​}​"​ ​י​ו​ב​א​ ​מ​{​s​o​u​r​c​e​}​ ​ו​נ​ט​ע​ן
		 * @param {string} name
		 * @param {string} source
		 */
		importedFrom: RequiredParams<'name' | 'source'>
		/**
		 * ק​ו​ב​ץ
		 */
		fileSource: string
		/**
		 * ט​ק​ס​ט
		 */
		textSource: string
		/**
		 * ש​ג​י​א​ה​ ​ב​י​י​ב​ו​א
		 */
		importError: string
		/**
		 * h​e​-​I​L
		 */
		dateLocale: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * 🎨 יוצר הבאנר
		 */
		title: () => LocalizedString
		/**
		 * עצב, התאם אישית וייצא
		 */
		subtitle: () => LocalizedString
		/**
		 * ייצוא PNG
		 */
		exportPng: () => LocalizedString
		/**
		 * מייצא...
		 */
		exporting: () => LocalizedString
		/**
		 * EN
		 */
		langSwitch: () => LocalizedString
	}
	tabs: {
		/**
		 * טקסט
		 */
		text: () => LocalizedString
		/**
		 * גודל
		 */
		size: () => LocalizedString
		/**
		 * רקע
		 */
		background: () => LocalizedString
		/**
		 * אייקונים
		 */
		icons: () => LocalizedString
		/**
		 * פריסטים
		 */
		presets: () => LocalizedString
	}
	text: {
		/**
		 * תוכן הטקסט
		 */
		content: () => LocalizedString
		/**
		 * הקלד את הטקסט שלך...
		 */
		placeholder: () => LocalizedString
		/**
		 * שורות חדשות נתמכות (Enter)
		 */
		newlineHint: () => LocalizedString
		/**
		 * גופן
		 */
		font: () => LocalizedString
		/**
		 * משקל גופן
		 */
		fontWeight: () => LocalizedString
		/**
		 * גודל גופן
		 */
		fontSize: () => LocalizedString
		/**
		 * צבע טקסט
		 */
		textColor: () => LocalizedString
		/**
		 * רווח בין אותיות
		 */
		letterSpacing: () => LocalizedString
		/**
		 * גובה שורה
		 */
		lineHeight: () => LocalizedString
		/**
		 * צל טקסט
		 */
		textShadow: () => LocalizedString
		weights: {
			/**
			 * דק
			 */
			thin: () => LocalizedString
			/**
			 * רגיל
			 */
			regular: () => LocalizedString
			/**
			 * בינוני
			 */
			medium: () => LocalizedString
			/**
			 * עבה
			 */
			bold: () => LocalizedString
			/**
			 * שחור
			 */
			black: () => LocalizedString
		}
	}
	size: {
		/**
		 * גדלים מוגדרים מראש
		 */
		presets: () => LocalizedString
		/**
		 * רוחב
		 */
		width: () => LocalizedString
		/**
		 * גובה
		 */
		height: () => LocalizedString
		/**
		 * עיגול פינות
		 */
		borderRadius: () => LocalizedString
	}
	background: {
		/**
		 * סוג רקע
		 */
		type: () => LocalizedString
		/**
		 * צבע אחיד
		 */
		solid: () => LocalizedString
		/**
		 * גרדיאנט
		 */
		gradient: () => LocalizedString
		/**
		 * צבע
		 */
		color: () => LocalizedString
		/**
		 * סוג גרדיאנט
		 */
		gradientType: () => LocalizedString
		/**
		 * קווי
		 */
		linear: () => LocalizedString
		/**
		 * רדיאלי
		 */
		radial: () => LocalizedString
		/**
		 * זווית
		 */
		angle: () => LocalizedString
		/**
		 * צורה
		 */
		shape: () => LocalizedString
		/**
		 * עיגול
		 */
		circle: () => LocalizedString
		/**
		 * אליפסה
		 */
		ellipse: () => LocalizedString
		/**
		 * עצירות צבע
		 */
		colorStops: () => LocalizedString
		/**
		 * הוסף עצירה
		 */
		addStop: () => LocalizedString
	}
	icons: {
		/**
		 * תמונות מותאמות אישית
		 */
		customImages: () => LocalizedString
		/**
		 * העלה תמונה
		 */
		uploadImage: () => LocalizedString
		/**
		 * טוען...
		 */
		uploading: () => LocalizedString
		/**
		 * אין תמונות — לחץ "העלה תמונה" כדי להוסיף
		 */
		noImages: () => LocalizedString
		/**
		 * ימין
		 */
		right: () => LocalizedString
		/**
		 * שמאל
		 */
		left: () => LocalizedString
		/**
		 * אייקון ימין
		 */
		rightIcon: () => LocalizedString
		/**
		 * אייקון שמאל
		 */
		leftIcon: () => LocalizedString
		/**
		 * ללא אייקון
		 */
		noIcon: () => LocalizedString
		/**
		 * הסר אייקון
		 */
		removeIcon: () => LocalizedString
		/**
		 * גודל אייקונים
		 */
		iconSize: () => LocalizedString
		/**
		 * מיקום (מהקצה)
		 */
		iconOffset: () => LocalizedString
		/**
		 * קצה
		 */
		offsetEdge: () => LocalizedString
		/**
		 * מרכז
		 */
		offsetCenter: () => LocalizedString
		groups: {
			/**
			 * חגיגה
			 */
			celebration: () => LocalizedString
			/**
			 * כוכבים
			 */
			stars: () => LocalizedString
			/**
			 * לבבות
			 */
			hearts: () => LocalizedString
			/**
			 * טבע
			 */
			nature: () => LocalizedString
			/**
			 * סמלים
			 */
			symbols: () => LocalizedString
			/**
			 * דגל
			 */
			flag: () => LocalizedString
			/**
			 * חיוכים
			 */
			smileys: () => LocalizedString
		}
	}
	presets: {
		/**
		 * שמור הגדרות נוכחיות כפריסט
		 */
		saveTitle: () => LocalizedString
		/**
		 * שם הפריסט...
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * שמור
		 */
		save: () => LocalizedString
		/**
		 * פריסטים שמורים ({count})
		 */
		savedTitle: (arg: { count: number }) => LocalizedString
		/**
		 * אין פריסטים שמורים עדיין
		 */
		noPresets: () => LocalizedString
		/**
		 * טען
		 */
		load: () => LocalizedString
		/**
		 * ייצוא JSON
		 */
		exportJson: () => LocalizedString
		/**
		 * מחק פריסט
		 */
		deletePreset: () => LocalizedString
		/**
		 * ייבוא פריסט
		 */
		importTitle: () => LocalizedString
		/**
		 * העלה קובץ JSON
		 */
		uploadJson: () => LocalizedString
		/**
		 * או
		 */
		orDivider: () => LocalizedString
		/**
		 * הדבק תוכן JSON ישירות
		 */
		pasteLabel: () => LocalizedString
		/**
		 * ייבא מטקסט
		 */
		importFromText: () => LocalizedString
		/**
		 * "{name}" יובא מ{source} ונטען
		 */
		importedFrom: (arg: { name: string, source: string }) => LocalizedString
		/**
		 * קובץ
		 */
		fileSource: () => LocalizedString
		/**
		 * טקסט
		 */
		textSource: () => LocalizedString
		/**
		 * שגיאה בייבוא
		 */
		importError: () => LocalizedString
		/**
		 * he-IL
		 */
		dateLocale: () => LocalizedString
	}
}

export type Formatters = {}
